title: The Monthly Digest
description: A minimalist approach to staying informed without the noise
# theme: jekyll-theme-minimal
baseurl: "/monthlydigest"
url: "https://scumborg.github.io"

# Optional but useful settings
author: Your Name
email: your-email@example.com

# Build settings
markdown: kramdown
