title: The Monthly Digest
description: A minimalist approach to staying informed without the noise
baseurl: "/monthlydigest"
url: "https://scumborg.github.io"

# Optional settings
author: Sean
email: your-email@example.com

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty