title: The Monthly Digest
description: A minimalist approach to staying informed without the noise
baseurl: "/monthlydigest"
url: "https://scumborg.github.io"
github_username: scumborg

# Build settings
markdown: kramdown

# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"